name: CI/CD

on: [push]

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
            steps:
            - uses: actions/checkout@v4
              ref: 'main'
            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: 'latest'
            - name: Install nodejs dependencies
              run: |
                  npm ci
            - name: Build
              run: |
                  npm run build
            - name: Test Signatures
              run: |
                  npm audit signatures
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
